### ISSUE TITLE
 InputBag::get() - wrong $default parameter

### ISSUE THREAD

**Issue by seb-jean** [phpstan/phpstan-symfony#214] opened 2021-12-01 13:05 UTC
Hi,

The parameter $default is `string|int|float|bool|null` and phpstan has "`string|null`".

**Comment by ondrejmirtes** [comment] 2021-12-01 13:08
What error message are you getting because of this?

**Comment by seb-jean** [comment] 2021-12-01 13:11
`message: "#^Parameter \\#2 \\$default of method Symfony\\\\Component\\\\HttpFoundation\\\\InputBag\\<string\\>\\:\\:get\\(\\) expects string\\|null, int given\\.$#"`

**Comment by ondrejmirtes** [comment] 2021-12-01 13:13
And the code that's causing this error? Also please make sure this is not just a duplicate of https://github.com/phpstan/phpstan-symfony/issues/201

**Comment by seb-jean** [comment] 2021-12-01 13:15
```php
$page = (int) $request->query->get('page', 1);
```

**Closed** 2022-01-08 20:26 UTC
