### ISSUE TITLE
Call to method Request::hasSession() will always evaluate to true.

### ISSUE THREAD

**Issue by mmarton** [phpstan/phpstan-symfony#86] opened 2020-06-08 15:52 UTC
I'm not entirely sure this is a phpstan related issue.

When I check for session, ie:
```php
 if ($request->hasSession()) {
     $request->getSession()->set('key', 'value');
}
```

I got the folllowing phpstan error:
> Call to method Symfony\Component\HttpFoundation\Request::hasSession() will always evaluate to true.

If I comment out the use of phpstan-symfony OR the phpstan-strict-rules plugin, the error disappears.

Maybe related to https://github.com/phpstan/phpstan-symfony/issues/56

Symfony version 5.0
Phpstan versions:
phpstan/phpdoc-parser 0.4.4
phpstan/phpstan 0.12.26
phpstan/phpstan-deprecation-rules 0.12.4
phpstan/phpstan-doctrine 0.12.14
phpstan/phpstan-strict-rules 0.12.2
phpstan/phpstan-symfony 0.12.6

**Comment by 9ae8sdf76** [comment] 2020-08-13 18:49
Same here. This is because Symfony defines the type as `SessionInterface` without it possibly being null. How can we work around this without disabling the remainder of the rules?

**Comment by ondrejmirtes** [comment] 2021-06-30 09:48
> This is because Symfony defines the type as SessionInterface without it possibly being null. 

This seems right. It's because of this extension: https://github.com/phpstan/phpstan-symfony/blob/9cd6919b8c695206dc24b5b5e8a082cd3b8f4c05/src/Type/Symfony/RequestTypeSpecifyingExtension.php

I think it was created back when `getSession()` returned nullable type in Symfony 4.x.

The extension should be modified to return empty `new SpecifiedTypes()` when the type is already non-nullable.

**Comment by VincentLanglet** [comment] 2021-06-30 09:53
> > This is because Symfony defines the type as SessionInterface without it possibly being null.
> 
> This seems right. It's because of this extension: https://github.com/phpstan/phpstan-symfony/blob/9cd6919b8c695206dc24b5b5e8a082cd3b8f4c05/src/Type/Symfony/RequestTypeSpecifyingExtension.php
> 
> I think it was created back when `getSession()` returned nullable type in Symfony 4.x.
> 
> The extension should be modified to return empty `new SpecifiedTypes()` when the type is already non-nullable.

In my project, I'm using Symfony 4.x ; so `getSession` is nullable.

And I'm curious how the `getSession` type specifier has an impact on the `hasSession` resolution

**Comment by ondrejmirtes** [comment] 2021-06-30 09:57
> And I'm curious how the getSession type specifier has an impact on the hasSession resolution

If you're narrowing down a type that's already the same type, you're getting this error. For example `is_int($int)` would report the same thing.

**Comment by ondrejmirtes** [comment] 2021-06-30 09:57
> In my project, I'm using Symfony 4.x ; so getSession is nullable.

In that case the PHPDoc above the method is wrong.

**Comment by VincentLanglet** [comment] 2021-06-30 10:05
Since the phpdoc is wrong in Symfony 4 and in Symfony 5 it's never nullable, can't we just remove this type specifier ?

**Comment by ondrejmirtes** [comment] 2021-06-30 11:47
It's marked as nullable in versions before 4.4: https://github.com/symfony/symfony/commit/f62a3c0810663b19c044488f407b3dfab0a53ba0#diff-779a02ff90f6fc60228d531d684382d3b585b3c823ba53028ff8d2a9e03a2ea0L705

**Comment by mmarton** [comment] 2021-06-30 12:03
below 4.4 versions are EOL-d: https://symfony.com/releases

**Comment by ondrejmirtes** [comment] 2021-06-30 12:04
I've told you what needs to be done to fix this:

> the extension should be modified to return empty new SpecifiedTypes() when the type is already non-nullable.

**Comment by VincentLanglet** [comment] 2021-06-30 12:11
> I've told you what needs to be done to fix this:
> 
> > the extension should be modified to return empty new SpecifiedTypes() when the type is already non-nullable.

Yes, I'm on it. I've some difficulties adding a failing test first.

```
assertType('bool', $request->hasSession());
```
is not failing when `$request->hasSession()` is considered as `true`.

What would be the right way to check that the method is considered as a bool and not as `true` ?

**Comment by ondrejmirtes** [comment] 2021-06-30 12:13
The problem should be reproducible with a test similar to this one: https://github.com/phpstan/phpstan-beberlei-assert/blob/master/tests/Type/BeberleiAssert/ImpossibleCheckTypeMethodCallRuleTest.php

**Comment by VincentLanglet** [comment] 2021-06-30 13:14
Done https://github.com/phpstan/phpstan-symfony/pull/181

**Closed** 2021-07-01 07:29 UTC
